class Items:
  def __init__(
    self, 
    name, 
    description, 
    slot,
    img_url, 
    element,
    rarity, 
    armor=0, 
    armor_per=0,
    health=0, 
    health_per=0,
    parry_L=0, 
    parry_H=0,  
    fail_L=0, 
    fail_H=0,
    damage_weapon=0,
    damage_L=0,
    damage_H=0,
    damage_S=0,
    final_damage_L=0,
    final_damage_H=0,
    final_damage_S=0,
    damage_per_L=0,
    damage_per_H=0,
    damage_per_S=0,
    letality_L=0,
    letality_H=0,
    letality_S=0,
    letality_per_L=0,
    letality_per_H=0,
    letality_per_S=0,
    crit_chance_L=0,
    crit_chance_H=0,
    crit_chance_S=0,
    crit_damage_L=0,
    crit_damage_H=0,
    crit_damage_S=0,
    special_charge_L=0,
    special_charge_H=0,
    special_charge_S=0,
    stacks_reduction=0,
    luck=0,
    vivacity=0
    ):
    self.name = name
    self.description = description
    self.slot = slot
    self.img_url = img_url
    self.element = element
    self.rarity = rarity
    self.bonuses = {
      "armor" : armor,
      "armor_per" : armor_per,
      "health" : health,
      "health_per" : health_per,
      "parry_L" : parry_L,
      "parry_H" : parry_H,
      "fail_L" : fail_L,
      "fail_H" : fail_H,
      "damage_weapon" : damage_weapon,
      "damage_L" : damage_L,
      "damage_H" : damage_H,
      "damage_S" : damage_S,
      "final_damage_L" : final_damage_L,
      "final_damage_H" : final_damage_H,
      "final_damage_S" : final_damage_S,
      "damage_per_L" : damage_per_L,
      "damage_per_H" : damage_per_H,
      "damage_per_S" : damage_per_S,
      "letality_L" : letality_L,
      "letality_H" : letality_H,
      "letality_S" : letality_S,
      "letality_per_L" : letality_per_L,
      "letality_per_H" : letality_per_H,
      "letality_per_S" : letality_per_S,
      "crit_chance_L" : crit_chance_L,
      "crit_chance_H" : crit_chance_H,
      "crit_chance_S" : crit_chance_S,
      "crit_damage_L" : crit_damage_L,
      "crit_damage_H" : crit_damage_H,
      "crit_damage_S" : crit_damage_S,
      "special_charge_L" : special_charge_L,
      "special_charge_H" : special_charge_H,
      "special_charge_S" : special_charge_S,
      "stacks_reduction" : stacks_reduction,
      "luck": luck,
      "vivacity": vivacity
    }
